language: r

cache: packages

# specify Partner Queue Solution to use free build minutes
# see: https://docs.travis-ci.com/user/billing-overview/#partner-queue-solution
os: linux
arch:
  - arm64
  - ppc64le
  - s390x

notifications:
  email:
    recipients:
      - joshua.hewitt@duke.edu
    on_failure: always

# branches:
#   only:
#     - master

latex: false  # Work around tlmgr issues.

install:
  - ./install_requirements.R
  - R CMD build nCompiler
  - R CMD INSTALL nCompiler --install-tests
  - Rscript -e 'library(nCompiler); setup_nCompLocal()'

script:
  - ./run_eigen_tests.R
