
## These are functions which may be called either from 'nCompiler' or from a
## package generated by 'nCompiler'.  It may ultimately be decided to include
## 'nCompiler' within generated packages, however, making this distinction
## irrelevant.


# Returns a list of reserved auxiliary function names. For now limited to serialization utilities.
getAuxFunNames <- function() {
  getSerialFunNames()
}


## Identifies indices of DLL helper functions.
## Returns vector with slot i ==  1/0 if funNames[i] is/isn't a helper function.
findDllNames <- function(funNames) {
  keep <- rep(1, if (is.list(funNames)) length(funNames) else 1)
  for(DLLname in getAuxFunNames()) {
    found <- grepl(DLLname, funNames)
    if(any(found)) {
      i <- which(found)
      if(length(i) != 1)
        stop(paste("Duplicates of function name ", DLLname, " found"));
      keep[i] <- 0
    }
  }
  keep
}
