
## These are functions which may be called either from 'nCompiler' or from a
## package generated by 'nCompiler'.  It may ultimately be decided to include
## 'nCompiler' within generated packages, however, making this distinction
## irrelevant.


## Identifies indices of DLL helper functions.
## Returns boolean with slot values T/F if funNames[i] is/isn't a helper.
findDllNames <- function(funNames, auxNames) {
  keep <- rep(TRUE, if (is.list(funNames)) length(funNames) else 1)
  for(DLLname in getAuxFunNames()) {
    found <- grepl(DLLname, funNames)
    if(any(found)) {
      i <- which(found)
      if(length(i) != 1)
        stop(paste("Auxilliary function ", DLLname, " is duplicated"));
      keep[i] <- FALSE
    }
  }
  keep
}
