
## These are functions which may be called either from 'nCompiler' or from a
## package generated by 'nCompiler'.  It may ultimately be decided to include
## 'nCompiler' within generated packages, however, making this distinction
## irrelevant.


#' @return new environment referencing DLL-scope auxiliary functions.
make_DLLenv <- function(dllFuns, pkgName) {
  dllEnv <- new.env(parent = getNamespace(pkgName))

  for (i in seq_along(dllFuns)) {
    dllEnv[[names(dllFuns)[i]]] <- dllFuns[i]
  }
  
  class(dllEnv) <- "nC_DLL_env"
  dllEnv
}


get_DLLenv <- function(obj) {
  parent.env(obj)
}


#' Stateful version of above.
#' @return DLL environment getter method.
dllEnvMgr <- function(dllFuns, pkgName) {
  dllEnv <- make_DLLenv(dllFuns, pkgName)

  ## Getter for the current DLL environment.
  getEnv <- function() {
    dllEnv
  }
}


#' Identifies indices of kept (non-DLL helper) function names.
#' @return boolean with values T/F as to whether name at index is/isn't kept.
findKeptNames <- function(funNames, auxNames) {
  keep <- rep(TRUE, if (is.list(funNames)) length(funNames) else 1)
  for(DLLname in auxNames) {
    found <- grepl(DLLname, funNames)
    if (any(found)) {
      i <- which(found)
      if(length(i) != 1)
        stop(paste("Auxilliary function ", DLLname, " is duplicated"));
      keep[i] <- FALSE
    }
  }
  keep
}
